[UNCAIM-88][Zhenjia Zhou] ci: adjust python path config

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -6,7 +6,7 @@ GREEN='\033[0;32m'
 YELLOW='\033[0;33m'
 RESET='\033[0m'
 
-echo  "${YELLOW}Running tests and checking coverage before pushing changes...${RESET}"
+echo "${YELLOW}Running tests and checking coverage before pushing changes...${RESET}"
 
 # Run pytest with coverage
 export PYTHONPATH=$(pwd)
@@ -16,9 +16,9 @@ pytest
 result=$?
 
 if [ $result -ne 0 ]; then
-    echo  "${RED}Tests failed or do not meet coverage threshold, please check and fix your code.${RESET}"
-    exit 1
+  echo "${RED}Tests failed or do not meet coverage threshold, please check and fix your code.${RESET}"
+  exit 1
 fi
 
-echo  "${GREEN}All checks passed. Proceeding with push...${RESET}"
+echo "${GREEN}All checks passed. Proceeding with push...${RESET}"
 exit 0
